import math

def main():
    size = 512
    filepath = "foc/math/foc_trig_lut.c"
    
    with open(filepath, "w", encoding="utf-8") as f:
        f.write("/* Automatically generated by gen_sin_lut.py. Do not edit. */\n")
        f.write('#include "foc_numeric.h"\n')
        f.write('#include "foc_trig.h"\n\n')
        f.write("#if (FOC_TRIG_BACKEND == FOC_TRIG_BACKEND_LUT)\n")
        f.write("const float s_afSinQuarter[513] = {\n")
        for i in range(size + 1):
            angle_rad = (i / size) * (math.pi / 2.0)
            val = math.sin(angle_rad)
            f.write(f"    {val:.9f}f,\n")
        f.write("};\n\n")
        
        # 写入插值算法
        f.write("float lut_sin_turns(float fTurns)\n")
        f.write("{\n")
        f.write("    float fPhase = fTurns * 4.0f;\n")
        f.write("    uint32_t wQuad = (uint32_t)fPhase;\n")
        f.write("    float fFrac = (fPhase - (float)wQuad) * 512.0f;\n")
        f.write("    uint32_t wIdx = (uint32_t)fFrac;\n")
        f.write("    float fLerp = fFrac - (float)wIdx;\n\n")
        f.write("    if (wQuad & 1) { /* 象限 1 和 3 */\n")
        f.write("        wIdx = 511 - wIdx;\n")
        f.write("        fLerp = 1.0f - fLerp;\n")
        f.write("    }\n\n")
        f.write("    float fY0 = s_afSinQuarter[wIdx];\n")
        f.write("    float fY1 = s_afSinQuarter[wIdx + 1];\n")
        f.write("    float fRes = fY0 + (fY1 - fY0) * fLerp;\n\n")
        f.write("    if (wQuad >= 2) { /* 象限 2 和 3 */\n")
        f.write("        fRes = -fRes;\n")
        f.write("    }\n")
        f.write("    return fRes;\n")
        f.write("}\n")
        f.write("#endif\n")

if __name__ == "__main__":
    main()
